### ISSUE TITLE
VOC07数据集检测map低

### ISSUE THREAD

**Issue by serena9525** [Yochengliu/MLIC-KD-WSD#12]
您好，感谢您的代码！　我们在VOC07 上训练了wsddn部分，测试发现分类的map有89.1%，但是检测的map只有６％，我们核对了输入格式，是路径＋分类label＋proposal_info(x_min y_min x_max y_max score)，proposal取的是置信度前500的edgebox．我们的初始的学习率是1e-5，loss下降也比较正常．

**Comment by Yochengliu** [comment]
你好，我们在VOC07上的最佳test loss为1.2左右。若你们复现的test loss与此接近，建议检查下计算检测mAP的脚本，我们是按照WSDDN/pascal/wsddnVOCevaldet.m写的。

https://github.com/hbilen/WSDDN/blob/master/pascal/wsddnVOCevaldet.m

**Comment by serena9525** [comment]
谢谢您的建议！我们在检查检测部分的脚本． 　我们按照wsddn原文，初始学习率设置为1e-5，10个epoch下降为1e-6，共训练20个epoch，但是得到test loss 1.5左右．您复现wsddn实际采用了怎样的的学习率，迭代次数？

**Comment by Yochengliu** [comment]
5e-5训练到test loss趋于平稳，再降10倍训练到test loss趋于平稳，只要test loss能下降就还可以降学习率。我们没有计数epoch，手动降学习率训练。
