### ISSUE TITLE
example in python

### ISSUE THREAD

**Issue by ShaihW** [Yochengliu/MLIC-KD-WSD#13]
1st thank you for sharing your code
I try to evaluate the code in python (using PyCaffe)
Is there an example code for how to use wsddn or MLIC as evaluator in python? (i.e. just input an image and get labels)
I see that there's a need in proposals in wsddn_deploy.prototxt but I cannot find a way to produce them
Thank you 

BTW - I succeed in installing the code on Ubuntu18.04 Cuda10 cudnn5.1 opencv3.1.0

**Comment by ShaihW** [comment]
Also - where can I find the weights for the layers after the VGG16 backbone?

**Comment by Yochengliu** [comment]
1. Sorry, there is no that example code, but it seems easy to implement. Below is the link that may be useful for you. 
https://stackoverflow.com/questions/32379878/cheat-sheet-for-caffe-pycaffe

2. We use EdgeBoxes algorithm to produce the proposals. It is released at:
https://github.com/pdollar/edges      or python version by thirdparty   
https://github.com/dculibrk/edge_boxes_with_python

3. Great, congratulations!

**Comment by Yochengliu** [comment]
4. For training, the weights after VGG16 backbone are initialized with Xavier algorithm [1].

[1] Glorot Xavier and Y. Bengio. 2010. Understanding the Difficulty of Training Deep Feedforward Neural Networks.Journal of Machine Learning Research.PP,9 (2010), 249–256.
