### ISSUE TITLE
coco数据集的评价指标MAP

### ISSUE THREAD

**Issue by wywywy01** [Yochengliu/MLIC-KD-WSD#2]
您好,请问下你们论文里面的coco数据集指标里面有一个指标是map,请问这个是哪一个版本的实现呢?在代码里面没有找到,是和voc2012的评价指标一样吗

**Comment by Yochengliu** [comment]
你好，我们使用的是开源代码 https://github.com/zhufengx/SRN_multilabel 提供的tools。
