### ISSUE TITLE
Is the image inputed to Edgebox resize to 672?

### ISSUE THREAD

**Issue by ztwe** [Yochengliu/MLIC-KD-WSD#6]
The question is shown as title.

When train T-WDet model, it upsamples to 736, 832 and downsamples to 480, 576.
Is that right?

Another question is：
are “train_672_mscoco_edge_box_score.txt” in  train_stage1.prototxt and 
“train_672_mscoco_withebscore.txt” in wsddn_train.prototxt the same file?

**Comment by Yochengliu** [comment]
Q1: We input original image to EdgeBoxes for acquiring proposal info. Then, the proposal info. is written into the datalist, and the coordinates are dynamically (and randomly) resized according to the setting in Caffe prototxt. This is implemented in Caffe source code. In short, anyway is ok, but remember to unify the image size and the coordinates. 

Q2: Yes.

**Comment by ztwe** [comment]
Thx！
