### ISSUE TITLE
train WSD error

### ISSUE THREAD

**Issue by ztwe** [Yochengliu/MLIC-KD-WSD#7]
GPU has 16GB memory.
The error is shown as following:

![image](https://user-images.githubusercontent.com/7899459/49562628-52b71000-f957-11e8-9972-f420ceed0800.png)

**Comment by Yochengliu** [comment]
You can decrease the batch_size in prototxt, or decrease the image size by modifying the new_height (new_width) and the scale_factors.

**Comment by ztwe** [comment]
Actually I have try batch_size=8 or 16, it showed the same error.
I will try smaller image size.

**Comment by ztwe** [comment]
It seems  work when both train and test batch_size set to 2.
But it is meaningless when batch_size=2.
How do you train the model with batce_size=32?
Are there any tricks?

**Comment by Yochengliu** [comment]
We use 16 GPUs to train and test. Maybe small batch_size is also ok, as in the WSDDN paper, they set batch_size = 1.

**Comment by ztwe** [comment]
Thx!

When I set the number of  GPU to be larger than 1, it still shows error and seems only GPU 0 has been really used.
In the output info , I find this line 'gpu x does not have p2p access to gpu x'.

**Comment by Yochengliu** [comment]
Caffe_MLIC is the official Caffe in which our implementation of MLIC-KD-WSD is merged. It may not well support multiple gpus. You can refer to some multi-gpu implementations of Caffe by searching "caffe multigpu" on github. The links below may be useful. 

https://github.com/BVLC/caffe/blob/master/docs/multigpu.md

**Comment by ztwe** [comment]
I had tried ’--gpu‘ before. It's useless.
Anyway, thank you very much!
